### ISSUE TITLE
add custom columns to EntryTable?

### ISSUE THREAD

**Issue by martino-vic** [martino-vic/gerstnerhungarian#4]
@LinguList I am trying to [add custom columns](https://github.com/martino-vic/gerstnerhungarian/blob/main/lexibank_gerstnerhungarian.py#L122) "Year", "Etymology", and "Loan" to the EntryTable, but nothing is happening. I guess I have to define those new columns somehow in the beginning with attr.ib but I'm not sure how to do that, or if it's possible at all to do something like this.

**Comment by LinguList** [comment]
Please check here: 

https://github.com/lexibank/allenbai/blob/b4deda3eb99b989c8a10b840fc38f2efd2dde823/lexibank_allenbai.py#L91-L98

This shows how you add columns to the writer. If it is the entry table, you reference it as EntryTable. Since this is the dictionary CLDF, you do no have the convenient attr.ib support we have in lexibank.

**Comment by martino-vic** [comment]
Ah, that worked really smoothly. Thank you! :)
